name: cadlab
channels:
  - defaults
  - cadquery
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.19.4
  - matplotlib=3.3.2
  - pip=20.2.4
  - notebook>=6.1.5,<6.2
  - jupyterlab>=2.2.9,<3
  - sidecar=0.4.0
  - ipywidgets=7.5.1
  - pythreejs>=2.2.1,<2.3
  - cadquery=2.1
  - flask
  - pip:
    - webcolors==1.11.1
    - git+https://github.com/bernhard-42/cadquery.git@assembly-hierarchy
    - git+https://github.com/bernhard-42/jupyter-cadquery.git@v2.0.0-beta3#egg=jupyter-cadquery
